language: node_js
node_js:
  - "lts/*"

dist: trusty
sudo: required

addons:
  chrome: stable

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

cache:
  directories:
    - node_modules

install:
  - npm install
